### ISSUE TITLE
.DMG link is dead 

### ISSUE THREAD

**Issue by hiteshkumarGE** [marius-m/wt4#11]
Hi, 

.dmg link is not working -> http://545149.s.dedikuoti.lt/wt4_download/macosx/WT4-4.0.dmg

Could you provide me the new link for the latest version. 

Thanks, 
Hitesh Kumar

**Comment by marius-m** [comment]
Hi, 

I'm so sorry I just now noticed the issue registered. I've updated the link and it should be working now: http://738649.s.dedikuoti.lt/wt4/WT4_mac.dmg . 

Cheers,
