### ISSUE TITLE
Jira cloud login with api token failing

### ISSUE THREAD

**Issue by vzailskas** [marius-m/wt4#14]
Logs:

`10:14:07.924 [RxIoScheduler-3] WARN  JIRA - Host or endpoint not found: Status: 404 / {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}}`

**Comment by marius-m** [comment]
Fixed the issue in 1.8.2; https://github.com/marius-m/wt4/releases/tag/1.8.2

Also profiles are fully separated, so you can launch multiple apps at once without sharing their config ♥️
Let me know if that helps
