### ISSUE TITLE
Download Links of Mac App is not working

### ISSUE THREAD

**Issue by jay2w** [marius-m/wt4#5]
It would be nice to be able to download the WT4 App für Mac. Thanks a lot.

**Comment by marius-m** [comment]
Im sorry, only now noticed the issue (no email notification). If you still need it, i've updated the links to dropbox. To download for mac, please use these: 
  - [Small installer] (https://www.dropbox.com/s/tgcomkvrl28fi0w/WT4-4.0.dmg?dl=0)
  - [Fat installer] (https://www.dropbox.com/s/0982iaqga9lithe/WT4-fat-4.0.dmg?dl=0)

The fat one bundles JRE together if you dont have java, or not want to bother installing it separately.

**Comment by jay2w** [comment]
thanks ;)
