### ISSUE TITLE
Fail to get right task when has number in board name

### ISSUE THREAD

**Issue by vitorlans** [marius-m/wt4#8]
Hi,
I'm having trouble to use wt4 when name of board has any number before number of task.
Like you can see on picture:
![image](https://user-images.githubusercontent.com/5940943/28873714-2be0bef6-7765-11e7-8768-b2092be38421.png)

![image](https://user-images.githubusercontent.com/5940943/28873821-8c765ffa-7765-11e7-860a-5f01690cda01.png)

Thanks.

**Comment by marius-m** [comment]
Hi, yeah if i remember correctly, its how its intended. It takes everything you type in by the symbol, so if you would delete the "-34", it would search correctly. 

I'm not sure how are you suggesting to improve this ? Maybe you could  elaborate ?
