### ISSUE TITLE
Crashes on first launch on MacOS High Sierra

### ISSUE THREAD

**Issue by trmazurkevych** [marius-m/wt4#9]
MacOS High Sierra 10.13.4
MacBook Pro 2015
Admin account

**Comment by marius-m** [comment]
So it seems that there are problems when running in Java10 and somehow the new High Sierra does not pick up bundled jre version. Ill try to figure something out and keep it posted.

**Comment by marius-m** [comment]
Ok, so apparently something has changed in app bundling process which resulted in failing to use bundled up JRE8 that is together with the app (it does not work on new JAVA9/JAVA10). As the process has changed, update library has been broken and it'll probably take time to get it fixed. 

So bad news, no more auto-update. Good news - new version should work properly. 
You can install it at: http://545149.s.dedikuoti.lt/wt4_download/macosx/WT4-4.0.dmg
